# Based on https://github.com/mvdan/github-actions-golang
on: [push, pull_request]
name: Tests
jobs:
  test:
    strategy:
      matrix:
        go-version: ['stable', 'oldstable']
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - run: |
          go install github.com/rogpeppe/go-internal/cmd/testscript@latest
          go install github.com/bitfield/txtar-c@latest
          ./run_all_testscripts.sh
